### ISSUE TITLE
Add option to register users with ProxySQL

### ISSUE THREAD

**Issue by ovaistariq** [twindb/proxysql-tools#20]
* ProxySQL Tools version: 0.2.13
* Python version: 2.7
* Operating System: CentOS 7

### Description

proxysql-tool should automatically register users in mysql.users table with ProxySQL.
A config option is needed so that it can set the appropriate default_hostgroup for users. This would allow query routing by users.

**Comment by akuzminsky** [comment]
Fixed in 0.3.10
