### ISSUE TITLE
Optimize galera scheduler

### ISSUE THREAD

**Issue by ovaistariq** [twindb/proxysql-tools#6]
**Based on chat with Rene:**

Both mine and Percona's Galera scheduler have a performance issue that I believe can cause high CPU usage. It calls LOAD MYSQL SERVERS TO RUNTIME always, no matter if any change was applied or not.
I will work on improving it, but as you are working on your own version I recommend to look into this optimization.

_LOAD MYSQL SERVERS TO RUNTIME is expensive. It needs to compare the new input table with what is already at runtime, find differences and correct them, and remove servers if necessary. It also signal all threads so that they can destroy immediately every connections to removed or offline servers._
So better not run it if not required.

**Comment by akuzminsky** [comment]
Fixed in 0.3.10
